# Generated by Django 4.0.5 on 2023-07-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=1000)),
                ('time', models.CharField(max_length=150)),
                ('device_type', models.CharField(max_length=250)),
                ('os', models.CharField(max_length=50)),
                ('browser', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=500)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Viewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=150)),
                ('device_type', models.CharField(max_length=250)),
                ('os', models.CharField(max_length=50)),
                ('browser', models.CharField(max_length=50)),
            ],
        ),
    ]
